### ISSUE TITLE
Feature Request: Regions Support

### ISSUE THREAD

**Issue by mphilipp622** [beaverlyhillsstudios/wavesurfer-blazor-wrapper#4]
I was wondering if support for adding regions could be implemented. Wavesurfer.js has a few methods in the regions plugin that are not present on this wrapper. https://wavesurfer-js.org/plugins/regions.html

Specifically, there's no way to add or clear regions. There are callbacks implemented for when regions are added and changed, but no direct methods on the object that allow you to add regions.

My specific use-case would be something like this:
```csharp
<WavesurferPlayer @ref="this.audioPlayer" />

@code{
    private WavesurferPlayer? audioPlayer;

    private async Task OnButtonClick()
    {
        await this.audioPlayer?.AddRegion(
            id: "region1",
            start: 3f,
            end: 6f,
            loop: false,
            drag: false,
            resize: false,
            color: "rgba(1, 0.5, 0.5, 1)",
            minLength: 3f,
            maxLength: 6f);
    }
}
```

Let me know if I can help with implementing this or if this functionality already exists and I'm just missing it. Thanks!

**Comment by rstefek** [comment]
Hello, 
we added minimal regions support we needed. But you got a point, that it makes sense to make that support complete.

I will create new development branch with that, and start implementation. You can cooperate on that with us, with mainly focused on testing, do you agree?

**Comment by mphilipp622** [comment]
Sounds good to me. Thank you.

**Comment by rstefek** [comment]
Hello, 
can you try to check current functionality in this branch?

https://github.com/beaverlyhillsstudios/wavesurfer-blazor-wrapper/tree/4-feature-request-regions-support

Small testing example provided:

```
<WavesurferPlayer ShowDefaultToolbar="true"
                    @ref="Player"
                    Url="sample.wav"
                    OnReady="PlayerReady"
                    RegionDragSelection="true" />

@code {
    public WavesurferPlayer Player { get; set; }

    public async void PlayerReady()
    {
        var region = await Player?.RegionAddRegion(
        new List<WavesurferRegionOption>
            {
                new WavesurferRegionOption(WavesurferRegionOptionKey.start, 60),
                new WavesurferRegionOption(WavesurferRegionOptionKey.end, 180.5),
                new WavesurferRegionOption(WavesurferRegionOptionKey.resize, true)
            }
        );
        StateHasChanged();
    }
}
```

**Comment by mphilipp622** [comment]
This appears to be working. Some things that might be helpful to include would be access to `wavesurfer.regions.list`, which provides a list of the current regions on the player, according to [the docs](https://wavesurfer-js.org/plugins/regions.html).

Additionally, I think statically typing the return type of the `RegionAddRegion` method would be nice. But this is a personal preference. I prefer static typing wherever possible. One way to implement it using `System.Text.JsonSerializer` would be defining a model like this:

```csharp
public record WavesurferRegion
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = Guid.NewGuid().ToString();

    [JsonPropertyName("start")]
    public float Start { get; init; } = 0f;

    [JsonPropertyName("end")]
    public float End { get; init; } = 0f;

    [JsonPropertyName("loop")]
    public bool? Loop { get; init; }

    [JsonPropertyName("drag")]
    public bool Drag { get; init; } = true;

    [JsonPropertyName("resize")]
    public bool Resize { get; init; } = true;

    [JsonPropertyName("color")]
    public string Color { get; init; } = "rgba(0,0,0,0.1)";

    [JsonPropertyName("channelIdx")]
    public int? ChannelId { get; init; }

    [JsonPropertyName("handleStyle")]
    public JsonElement? HandleStyle { get; init; }

    [JsonPropertyName("preventContextMenu")]
    public bool? PreventContextMenu { get; init; } = false;

    [JsonPropertyName("showTooltip")]
    public bool ShowTooltip { get; init; } = true;
}
```

This model is defined in the [wavesurfer docs](https://wavesurfer-js.org/api/typedef/index.html#static-typedef-RegionParams).

and then modifying the `WavesurferPlayer.RegionAddRegion` method to something like this:
```csharp
public async Task<WavesurferRegion?> RegionAddRegion(IEnumerable<WavesurferRegionOption>? regionOptions)
 {
    object? obj = await CallMethodInterop<object>("regionAddRegion", WavesurferRegionOptionsService.GetObjectFromRecords(regionOptions));

    if (obj == null) return null;
        
    string stringified = JsonSerializer.Serialize(obj);

    return JsonSerializer.Deserialize<WavesurferRegion>(stringified);
}
```

Of course, there may be better ways to do the static typing.

**Comment by rstefek** [comment]
Hello, since all returned region data goes through this code:
```
function getRegionDataOnly(regionFull) {
    return {
        id: regionFull.id,
        start: regionFull.start,
        end: regionFull.end,
        loop: regionFull.loop,
        drag: regionFull.drag,
        resize: regionFull.resize,
        color: regionFull.color,
        channelIdx: regionFull.channelIdx,
        handleStyle: regionFull.handleStyle,
        preventContextMenu: regionFull.preventContextMenu,
        showTooltip: regionFull.showTooltip
    }
}
```
I prefer to create given typed object here. Statical typing is a good idea and I agree it would be better. Expect new version for test this week :) You can later help with changes through PR if you want ;)

**Comment by rstefek** [comment]
Oh, that is JS, my fault :) Will try something or use your idea.

**Comment by rstefek** [comment]
So I get something from you and used automatic Blazor conversion of JSON, so no need to serialize and deserialize. Thanks for cooperation. Seems usable now. Let me know, I can merge this to main and make a new package version.

**Comment by mphilipp622** [comment]
It seems to be good. One thing I messed up on the WavesurferRegion record is that the properties should probably be `{get; set;}` instead of `{get; init;}` so that individual regions could be modified and the player refreshed.

You'd mentioned that I can make PR's. Should I go ahead and work on some of these things on my own and make a PR for review? Thanks.

**Comment by rstefek** [comment]
Converted region object is not directly connected to JS, so changes in it will not propagate back. I will try to prepare a mechanism for that and test it. You can definitely prepare PR's for contribution in case you will still miss something.

**Comment by mphilipp622** [comment]
Sounds good. If updating the regions is too complicated, then I think the support you implemented so far is good enough to put into a new release, for sure.

**Comment by rstefek** [comment]
Actual version was merged to main branch and released, I will definitely look to updates, because it is a feature that makes sense :)

**Comment by rstefek** [comment]
Updated Regions support - you can list and then update region list from .NET code. See updated README for example.
