### ISSUE TITLE
Feature Request: Markers Support

### ISSUE THREAD

**Issue by bryan-arn** [beaverlyhillsstudios/wavesurfer-blazor-wrapper#5]
Hi guys, great wrapper, was not looking forward to JS Interop to use Wavesurfer. Are there any plans to implement the Markers plugin per https://wavesurfer-js.org/plugins/markers.html ? That would really make my day :) Unless it's there, and I just can't see it....

**Comment by rstefek** [comment]
Hello Bryan,
thanks for catching up. We are currently implementing things based on our own needs, but markers are right after regions :) So you can expect it in later release this year.

**Comment by bryan-arn** [comment]
Thanks guys, sounds great. And thanks for making this a public repo!

**Comment by rstefek** [comment]
Hello,
marker support added to new release 0.3.0
Please check documentation changes for info.

**Comment by bryan-arn** [comment]
This is so great! Just one thing - the documentation at http://wavesurfer-js.org/api/typedef/index.html#static-typedef-MarkerParams shows a 'draggable' parameter (bool). Is there any chance that can be added?

**Comment by rstefek** [comment]
Hello, 
I added support according to plugin code.

You can find it in repository branch: https://github.com/beaverlyhillsstudios/wavesurfer-blazor-wrapper/tree/5-feature-request-markers-support

But I have no luck of getting marker to be draggable even if it is correctly set :/ So you can check if it works in your case. Can be some inter-plugin incompatibility.

**Comment by rstefek** [comment]
So it is issue in Wavesurfer plugin :/
https://github.com/katspaugh/wavesurfer.js/issues/2560

**Comment by bryan-arn** [comment]
So I have seen the bug - but as a workaround have added an initial marker in wavesurfer-use.js:
```
if (showMarkers) {
        options.plugins.push(
            WaveSurfer.markers.create({
                markers: [
                    {
                        color: "#FFFFFF",
                        draggable: true
                    }
                ]
            })
        );

    };
```

And then simply use MarkerClearMarkers in the OnInitializedAsync method. Not the most desirable fix but will get me by :) Thanks for the work, and hopefully Wavesurfer will fix their bug :)

Bryan

**Comment by rstefek** [comment]
I managed to make a pull request. So as soon as new release is done on main wavesurfer repositories, I will update our wrapper.
